Updated github action

diff --git a/.github/workflows/main_regnxtbirdportald.yml b/.github/workflows/main_regnxtbirdportald.yml
--- a/.github/workflows/main_regnxtbirdportald.yml
+++ b/.github/workflows/main_regnxtbirdportald.yml
@@ -26,6 +26,14 @@ jobs:
           echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
           echo "VITE_FAST_API_BACKEND=${{ secrets.VITE_FAST_API_BACKEND }}" >> .env
 
+      - name: Check .env file
+        run: |
+          if grep -q VITE_API_BASE_URL .env && grep -q VITE_FAST_API_BACKEND .env; then
+            echo "Both environment variables are present in .env file"
+          else
+            echo "One or both environment variables are missing from .env file"
+            exit 1
+          fi
       - name: npm install, build, and test
         run: |
           npm install
